Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
    UdacityS3ReadOnlyEC2:
        Type: AWS::IAM::Role
        Properties:
            ManagedPolicyArns: 
                - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
            RoleName: udacityS3ReadOnlyEC2
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: "Allow"
                      Principal:
                          Service:
                              - "ec2.amazonaws.com"
                      Action:
                          - "sts:AssumeRole"

    UdacityWebAppProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            InstanceProfileName: udacityWebAppProfile
            Roles:
                - !Ref UdacityS3ReadOnlyEC2
Outputs:
    UdacityWebAppProfile:
        Description: A reference to the created IAM instance profile
        Value: !Ref UdacityWebAppProfile
        Export:
            Name: !Sub ${EnvironmentName}-UdacityWebAppProfile
